/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'arno.diederik' at '7-10-16 11:04' with Gradle 2.4
 *
 * @author arno.diederik, @date 7-10-16 11:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
